/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _Included_com_andnux_core_utils_ImageUtils */

#ifndef _Included_com_andnux_core_utils_ImageUtils
#define _Included_com_andnux_core_utils_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL
Java_com_andnux_core_utils_ImageUtils_cjpegMain(JNIEnv, jclass , jint ,jobjectArray ) ;

JNIEXPORT jint JNICALL
Java_com_andnux_core_utils_ImageUtils_djpegMain(JNIEnv , jclass , jint,jobjectArray);

JNIEXPORT void JNICALL
Java_com_andnux_core_utils_ImageUtils_compress(JNIEnv , jclass , jobject ,jint ,jint ,jint ,jstring, jboolean );
#ifdef __cplusplus
}
#endif
#endif
