/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andnux_core_fix_DexManager */

#ifndef _Included_com_andnux_core_fix_DexManager
#define _Included_com_andnux_core_fix_DexManager



#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andnux_core_fix_DexManager
 * Method:    fixNative
 * Signature: (ILjava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_andnux_core_fix_DexManager_fixNative
  (JNIEnv *, jobject, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
